apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-app
        image: fastapi-app:minikube
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"  # Reference the Redis service name
        - name: REDIS_PORT
          value: "6379"  # Adjust based on your Redis configuration

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
